---

- name: Wait 300 seconds for SSH to be up
  wait_for_connection:
    timeout: 300

- name: Install dependencies
  apt:
    pkg: 
      - python3
      - python3-pip
      - mosh 
      - mg 
      - screen 
      - git
      - magic-wormhole
      - ffmpeg
    state: present
    update_cache: yes

- name: Download b2-linux
  ansible.builtin.get_url:
    url: https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux
    dest: /usr/local/bin/b2-linux

- name: Mark b2-linux as executable
  ansible.builtin.file:
    path: /usr/local/bin/b2-linux
    owner: root
    group: root
    mode: '0755'

- name: Add b2 key ID
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "export B2_APPLICATION_KEY={{ lookup('env', 'B2_APPLICATION_KEY') }}"
    state: present

- name: Add b2 application key
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "export B2_APPLICATION_KEY_ID={{ lookup('env', 'B2_APPLICATION_KEY_ID') }}"
    state: present

- name: Download screen configuration
  git:
    repo: 'https://github.com/insanity54/dotfiles'
    dest: /root/dotfiles

- name: Configure screen
  copy:
    src: /root/dotfiles/.screenrc
    dest: /root/.screenrc
    remote_src: yes

- name: Install & update youtube-dl
  pip:
    name: youtube-dl
    state: latest

- name: Install & update voddo
  git:
    repo: 'https://github.com/insanity54/voddo'
    dest: /root/voddo

- name: Install voddo system service
  ansible.builtin.template:
    src: templates/voddo.service.j2
    dest: /etc/systemd/system/voddo.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart voddo

- name: Enable voddo system service
  systemd:
    name: voddo
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart voddo

- name: Enable journalctl persistent logging
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    search_string: '^Storage='
    line: 'Storage=persistent'
    state: present
  notify: 
    - restart systemd-journald


