---

- name: Install dependencies
  apt:
    pkg: 
      - python3
      - python3-pip
      - mosh 
      - mg 
      - screen 
      - git
      - magic-wormhole
    state: present
    update_cache: yes

- name: Download screen configuration
  git:
    repo: 'https://github.com/insanity54/dotfiles'
    dest: /root/dotfiles

- name: Configure screen
  copy:
    src: /root/dotfiles/.screenrc
    dest: /root/.screenrc
    remote_src: yes

- name: Install & update youtube-dl
  pip:
    name: youtube-dl
    state: latest

- name: Install & update voddo
  git:
    repo: 'https://github.com/insanity54/voddo'
    dest: /root/voddo

- name: Install voddo system service
  ansible.builtin.template:
    src: templates/voddo.service.j2
    dest: /etc/systemd/system/voddo.service
    owner: root
    group: root
    mode: '0755'

- name: Enable voddo system service
  systemd:
    name: voddo
    state: started
    daemon_reload: yes
    enabled: yes